dist: trusty
sudo: false
lanquage: php
php:
  - '5.6'
  - '7.0'
  - '7.1'

services:
  - mysql

before_script:
  - mysql --version
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - mysql test < sql/structure_gepi.sql
  - mysql test < sql/data_gepi.sql

script:
  - cd test; phpunit testsuite
